### PR TITLE
[WIP] Move delay to segmented button

### PR DESCRIPTION
**Pull request by PlugaruT**
Basically this is what I have done till now.
I know that is not like it is described in #116, but I don't know what to use for the dropdown thing. Any suggestions?

image

### CODE REVIEW

**Comment by PlugaruT** [comment]
Basically everything works as expected but I need help on what Gtk widget to use in order to respect the design from #116. Can anyone give me some hints?

**Comment by naaando** [comment]
I saw this widget and found it very awesome so I made it in my app, but I think would be better to push it to granite instead then use it here, what do you think?

**Comment by PlugaruT** [comment]
Well, I don't mind doing that... But I do need help implementing that.

**Comment by naaando** [comment]
Well, I'm struggling to put style classes in it without relying on a specific method, but I implemented it with Gtk.Box with a Gtk.Button and a Gtk.ModalButton
The popup position is pointed down but it can be changed to match you mockup.
P.S

image

```cs
public class SegmentedButton : Gtk.Box {
    public signal void clicked (Gtk.Button button);

    Gtk.Button primary_button;
    Gtk.MenuButton menu_button;
    GLib.Menu menu;

    construct {
        get_style_context ().add_class ("segmented");
        get_style_context ().add_class (Gtk.STYLE_CLASS_LINKED);
        hexpand = false;
    }

    public SegmentedButton (string label, string? icon_name = null) {
        menu = new GLib.Menu ();

        primary_button = new Gtk.Button.with_label (label);
        primary_button.hexpand = true;
        primary_button.clicked.connect ((button) => on_primary_button_clicked (button));

        menu_button = new Gtk.MenuButton ();
        menu_button.image = new Gtk.Image.from_icon_name (icon_name, Gtk.IconSize.BUTTON);
        menu_button.set_menu_model (menu);

        add (primary_button);
        add (menu_button);
    }

    public void add_action (string label, string action_name) {
        if (!("." in action_name)) {
            warning ("Missing action namespace, if your action is on GLib.Application, it should look like app.action-name");
        }

        menu.append (label, action_name);
    }

    public void add_menu_item (MenuItem item) {
        menu.append_item (item);
    }

    public GLib.Menu get_menu () {
        return menu;
    }

    void on_primary_button_clicked (Gtk.Button button) {
        clicked (button);
    }
}
```

**Comment by naaando** [comment]
I think its the default behavior when it knows the window won't have space to open it, I don't know how to tweak this either.

**Comment by PlugaruT** [comment]
So, what can I do with this PR?
CC @naaando, @cassidyjames, @danrabbit

**Comment by cassidyjames** [comment]
In the prototype, @danrabbit had just used a menu, not a popover. I think that's still an appropriate decision.

**Comment by PlugaruT** [comment]
Oh, had no idea about that :) 
I'll try to change to using a menu instead

**Pull request closed without merging**
