### PR TITLE
Use Gala for taking screenshots

### PR DESCRIPTION
**Pull request by Exalm**
Makes Screenshot take screenshots by talking to Gala via dbus instead fo taking them manually.

This works on X11 as well, but has a few limitations/regressions:

* There's no way to grab mouse pointer with area screenshots. Should this be greyed out?
* I got an empty screenshot when trying to screenshot a window once, wasn't able to reproduce it anymore though

Fixes https://github.com/elementary/screenshot/issues/103

Fixes https://github.com/elementary/screenshot/issues/148

### CODE REVIEW

**Comment by Exalm** [comment]
Ha ha, trying to capture a window on an empty workspace crashes Gala. However, it's a bug in Gala, since there's no way to find this out from the app.

**Comment by cassidyjames** [comment]
>There's no way to grab mouse pointer with area screenshots. Should this be greyed out?

I would say remove the option when running on Wayland. We make widgets insensitive when there is something the user can to do enable it, but in this case switching display managers isn't really something we'd expect the user to do.

**Comment by Exalm** [comment]
> I would say remove the option when running on Wayland. We make widgets insensitive when there is something the user can to do enable it, but in this case switching display managers isn't really something we'd expect the user to do.

It's only for area screenshots though. It does work for screenshots of the whole screen or a window.

**Comment by Exalm** [comment]
gnome-screenshot handles it like this:

Screenshot from 2019-11-04 21-04-26

Screenshot from 2019-11-04 21-04-27

**Comment by danrabbit** [comment]
Yeah it's kind of odd that delay is also not available for area screenshots. If it's not technically possible to have these options available for area screenshots, then I would say making those options temporarily insensitive is the best way forward

**Comment by Exalm** [comment]
Delay is weird, because it should really be available. It's done client side anyway, so it can't be impossible :) And it's not like you first select the area, then have the delay, it's the other way. Though maybe it was this way in gnome-screenshot when it was X11-only, I don't know.

Mouse pointer, on the other hand... Well, look at the method signatures. `screenshot()` and `screenshot_window()` have the `include_cursor` parameter, `screenshot_area` doesn't.

I guess the rationale for not including it was that you're drawing the area with your cursor anyway.

**Comment by danrabbit** [comment]
Yeah, but that's the issue is that for capturing the cursor to make sense you need to add delay. So the user behavior there is that they do select the area first and then position their cursor during the delay.

But yeah, seeing that it's not available in the interface, I guess we have to lose this feature :)

**Comment by Exalm** [comment]
Screenshot from 2019-11-04 22-34-02

At this point it was definitely done fully client-side, and the delay already wasn't there. Oh well, I guess we'll never know. Either way, I think there is a value in having a delay even before you select a rectangle, since it gives you a chance to position your windows/open the menu you wanted to screenshot/open multitasking view/etc.

**Comment by Exalm** [comment]
Oh wait, it is after selecting the area in master. Since selection is a separate call, it is indeed possible to have this, so another regression it is then.

**Comment by Exalm** [comment]
Fixed area screenshot wrt delay.

> I got an empty screenshot when trying to screenshot a window once, wasn't able to reproduce it anymore though

Found out how to reproduce it. Take a window screenshot when concealing text.

**Comment by Exalm** [comment]
I've split everything backend into `ScreenshotBackend`, since it was getting confusing.

Conceal text should work correctly now, and I've removed the opacity hack.

**Comment by Exalm** [comment]
Moved concealing text to Gala too. Now it can also be flatpaked easily, only needing to whitelist `org.gnome.Shell.Screenshot` dbus name. If `ScreenshotAreaWithCursor()` doesn't exist (e.g. if you run it in gnome-shell), it falls back to `ScreenshotArea()`, if `ConcealText()` doesn't exist, it just takes unredacted screenshot (can change to show an error instead).

**Comment by danrabbit** [comment]
@Exalm is it possible to check if `ConcealText` exists and hide the option in the UI if it doesn't?

**Comment by Exalm** [comment]
Should be possible. What about rectangle+cursor?

**Comment by danrabbit** [comment]
@Exalm Yeah I'd say if that option is not available, the delay should be made insensitive while area is selected

**Comment by Exalm** [comment]
Well, delay is fine, it's the "include cursor".

**Comment by danrabbit** [comment]
@Exalm er yeah that's what I meant. Sorry :)

**Comment by Exalm** [comment]
Screenshot from 2019-12-19 15-51-26

Involves some ugly xml parsing + libxml2 dep though. :(

**Comment by danrabbit** [comment]
From @tintou in slack:

```
var introspectable_proxy = Bus.get_proxy_sync<IntrospectableProxy> (…)
unowned GLib.DBusProxy dbus_proxy = (GLib.DBusProxy) introspectable_proxy;
if (dbus_proxy.get_interface_info ().lookup_method ("ConcealText") != null)
```

or if you want to look even more clever and provide a one-liner against this parsing + new dependency:
```
if (((GLib.DBusProxy) introspectable_proxy).get_interface_info ().lookup_method ("ConcealText") != null)
```

**Comment by Exalm** [comment]
Oh wow. I actually did not know I could do that. Makes sense, thanks

**Comment by Exalm** [comment]
Wait. No, that's not correct. `lookup_method()` seems to check whether the method exists in the Vala interface, and not if it actually exists remotely.

**Comment by Exalm** [comment]
However, that API is indeed useful for parsing the xml instead of doing it manually. So calling `Introspect`, then using https://valadoc.org/gio-2.0/GLib.DBusNodeInfo.DBusNodeInfo.for_xml.html on the result, looking up the correct interface there and calling `lookup_method()` for _that_ object works.

**Comment by tintou** [comment]
Sorry, I've not looked thoroughly at it, but I think that it's not good to abuse the org.gnome namespace with our own functions.
If we want to add other functions, we have to add our own interface in a different namespace.
we can still use `org.gnome.Shell.Screenshot` for screenshots but we have to use something else (`io.elementary.gala.screenshot`?) for the non-GNOME API.
In the far future we might just end-up not using `org.gnome.Shell.Screenshot` as there will be a portal for screenshot that would do the shell integration for us.

**Comment by Exalm** [comment]
That's indeed true, the existing interface was chosen just for simplicity.

Portal won't help here though, because the portal itself will have to be implemented using the same dbus API.

**Comment by danrabbit** [comment]
Okay, it sounds like we want to fix https://github.com/elementary/gala/issues/677 before proceeding here

**Pull request merged**
